services:
  - type: web
    name: e-card-cutter
    env: python
    region: singapore
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
