services:
  - type: web
    name: e-card-cutter
    env: python
    buildCommand: |
      apt-get update && apt-get install -y poppler-utils
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python app.py
