services:
  - type: web
    name: e-card-cutter
    env: python
    plan: free
    region: singapore
    buildCommand: "apt-get update && apt-get install -y poppler-utils && pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
